### PR TITLE
GMS1 things

### PR DESCRIPTION
**Pull request by DragoniteSpam**
Backwards porting is the best

### CODE REVIEW

**Comment by JujuAdams** [comment]
PR is to delete the entire master branch as, as such, cannot be accepted. Can't imagine this was intentional!

**Comment by DragoniteSpam** [comment]
Comptuers is hard okay

**Comment by evolutionleo** [comment]
holy crap this is comedy gold

**Comment by DragoniteSpam** [comment]
update: computers is still hard

**Pull request closed without merging**
